=== mdujovic17/ISTProjekatV2/ads.dtd
<!ELEMENT ads (ad)+>
<!ATTLIST ads xmlns:xsi                     CDATA "http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation CDATA "ads.xsd">
<!ELEMENT ad (category, date, price, description, tags, e-mails)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency CDATA "RSD">
<!ELEMENT description (#PCDATA)>
<!ELEMENT tags (tag)+>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT e-mails (e-mail)+>
<!ELEMENT e-mail (#PCDATA)>
<!ATTLIST e-mail type (private|work) #REQUIRED>

=== mdujovic17/ISTProjekatV2/ads.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ads SYSTEM "ads.dtd">
<ads xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ads.xsd">
    <ad>
        <category>Automobili</category>
        <date>2004-06-25</date>
        <price currency="RSD">123.45</price>
        <description>Deset karaktera</description>
        <tags>
            <tag>dat</tag>
        </tags>
        <e-mails>
            <e-mail type="private">email@email.com</e-mail>
        </e-mails>
    </ad>
</ads>
